# **Arrays - Mòdul Numpy**

https://numpy.org/doc/stable/user/whatisnumpy.html

- Mòdul per poder treballar amb arrays multidimensionals (tipus `ndarray`)
- Què és un array?
   - És un tipus de dades compost definit a partir d’altres tipus de dades, en què els elements estan ordenats segons     una seqüència definida per l’índex de l’element (igual que a les llistes).
   
   <img src="./imatges_notebook/image1.png" alt="image 1" width="300" height="30" > 

   - Són objectes mutables.
   - A diferència de les llistes, els elements d’un array han de ser tots del mateix tipus de dades
   - Permeten representar i manipular fàcilment estructures multidimensionals: 1D, 2D, 3D, ... nD
   
   <img src="./imatges_notebook/image2.png" alt="image 1" width="400" height="160" > 
   
   - `numpy` incorpora una extensa llibreria de funcions per manipular i fer càlculs sobre arrays de forma molt eficient
  

In [3]:
import numpy as np

**Exemple**

In [4]:
a = np.empty(10)
print(a)

[2.33644978e-307 8.34428586e-308 1.50199021e-307 2.33647694e-307
 1.89142482e-307 2.11389826e-307 8.34427737e-308 1.50199531e-307
 2.33643960e-307 4.22789158e-307]


In [5]:
for i in range(10):
    a[i] = i * 10
print(a)

[ 0. 10. 20. 30. 40. 50. 60. 70. 80. 90.]


In [ ]:
for i in range(10):
    print(a[i])

In [6]:
a = np.empty((3, 4))
print(a)

[[1.05103434e-311 3.16202013e-322 0.00000000e+000 0.00000000e+000]
 [3.14573925e+097 3.06185043e-057 2.85471763e-056 3.37560468e-057]
 [3.59726042e+179 1.19055317e-047 1.15455572e-071 1.04113536e-071]]


In [7]:
for i in range(3):
    for j in range(4):
        a[i,j] = i * 10 + j
print(a)

[[ 0.  1.  2.  3.]
 [10. 11. 12. 13.]
 [20. 21. 22. 23.]]


In [8]:
a = np.empty((2, 3, 4))
print(a)

[[[6.23042070e-307 3.56043053e-307 1.60219306e-306 7.56571288e-307]
  [1.89146896e-307 1.37961302e-306 1.05699242e-307 8.01097889e-307]
  [1.78020169e-306 7.56601165e-307 1.02359984e-306 1.33510679e-306]]

 [[2.22522597e-306 1.33511018e-306 6.23057689e-307 1.11260755e-306]
  [8.34453626e-308 1.33508761e-307 1.33511562e-306 8.90103560e-307]
  [1.42410974e-306 1.00132228e-307 1.33511969e-306 2.18568966e-312]]]


### **Arrays: Creació**
https://docs.scipy.org/doc/numpy/user/quickstart.html#array-creation

**A partir de llistes**
- L'array s'inicialitza amb els valors de la llista que s'indica al moment de crear-lo

In [ ]:
a = np.array([1, 2, 3])
print (a)

- Si la llista és una llista de llistes, cada llista és una fila de l'array

In [9]:
b = np.array([[0, 2, 4, 6, 8], [1, 3, 5, 7, 9], [10, 12, 14, 16, 18]])
print (b)

[[ 0  2  4  6  8]
 [ 1  3  5  7  9]
 [10 12 14 16 18]]


**Especificant un rang de valors**
```python
arange(valorInicial, valorFinal, pasActualitzacio)
```
- Similar a la funció `range` de les llistes, però retorna un array i tots els valors poden ser decimals

In [ ]:
c = np.array([np.arange(0,1,0.2), np.arange(0.1,1.0,0.2), np.arange(1,2,0.2)])
print (c)

**Exercici**: Incialitzar un array de 4 files i 5 columnes amb valors del 1 al 20 guardats en ordre creixent per les files (la primera fila té els valors del 1 al 4 i la última fila els valors del 17 al 20).

In [ ]:
a = np.array([range(1,6), range(6,11), range(11, 16), range(16,21)])
print(a)

**A partir de valors fixos**
- Podem inicialitzar un array amb 0's ó 1's amb les funcions `np.zeros` i `np.ones` indicant en una tupla les dimensions de l'array

In [10]:
a = np.zeros((3,4))
print (a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
b = np.ones((2,3))
print (b)

[[1. 1. 1.]
 [1. 1. 1.]]


- Podem especificar el tipus dels valors de l'array (per defecte `float64`)
- Altres possibles tipus: https://docs.scipy.org/doc/numpy/reference/arrays.scalars.html

In [ ]:
b = np.ones((2,3), dtype='int32')
print (b)

**Com un array sense inicialitzar**
- Indicant en una tupla les dimensions de l'array

In [12]:
c = np.empty((2,2))
print (c)

[[1.05101527e-311 1.05103364e-311]
 [0.00000000e+000 1.06099790e-314]]


**Exercici**: Inicialitzar un array de 5 files i 4 columnes amb tots els valors inicialitzats a 10

In [13]:
a = np.ones((5, 4)) * 10
print(a)

[[10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]]


### **Arrays: Accés**
https://docs.scipy.org/doc/numpy/user/quickstart.html#indexing-slicing-and-iterating

Accés a un element de  l’array: un índex per cada dimensió (en 2D, fila i columna)
- Els índexs comencen per 0.
- Els índexs negatius comencen pel final de l’array

In [14]:
a = np.array([np.arange(0,10,2), np.arange(1,10,2), np.arange(10,20,2)])
print(a)
print(a[1,2])
print(a[-1,-2])

[[ 0  2  4  6  8]
 [ 1  3  5  7  9]
 [10 12 14 16 18]]
5
16


In [15]:
a = np.empty((3, 4, 2))
print(a)

[[[6.23042070e-307 3.56043053e-307]
  [1.60219306e-306 7.56571288e-307]
  [1.89146896e-307 1.37961302e-306]
  [1.05699242e-307 8.01097889e-307]]

 [[1.78020169e-306 7.56601165e-307]
  [1.02359984e-306 1.33510679e-306]
  [2.22522597e-306 1.33511018e-306]
  [6.23057689e-307 1.11260755e-306]]

 [[8.34453626e-308 1.33508761e-307]
  [1.33511562e-306 8.90103560e-307]
  [1.42410974e-306 1.00132228e-307]
  [1.33511969e-306 2.18568966e-312]]]


In [16]:
a[1,2,0] = 0
print(a)

[[[6.23042070e-307 3.56043053e-307]
  [1.60219306e-306 7.56571288e-307]
  [1.89146896e-307 1.37961302e-306]
  [1.05699242e-307 8.01097889e-307]]

 [[1.78020169e-306 7.56601165e-307]
  [1.02359984e-306 1.33510679e-306]
  [0.00000000e+000 1.33511018e-306]
  [6.23057689e-307 1.11260755e-306]]

 [[8.34453626e-308 1.33508761e-307]
  [1.33511562e-306 8.90103560e-307]
  [1.42410974e-306 1.00132228e-307]
  [1.33511969e-306 2.18568966e-312]]]


**Slicing**

Permet accedir a múltiples elements de l’array a la vegada:
- Per cada dimensió:  `inici:final:pas_actualització`
- Podem recuperar elements no consecutius definint un pas d'actualització diferent de 1. 

In [17]:
a = np.array([np.arange(0,10,2), np.arange(1,10,2), np.arange(10,20,2)])
print(a)

[[ 0  2  4  6  8]
 [ 1  3  5  7  9]
 [10 12 14 16 18]]


In [18]:
print (a[0,:])

[0 2 4 6 8]


In [19]:
print (a[0:2,:])

[[0 2 4 6 8]
 [1 3 5 7 9]]


In [20]:
print (a[0:2,0:5:2])

[[0 4 8]
 [1 5 9]]


**Exercici**: Incialitzar un array de 4 files i 5 columnes amb valors del 1 al 20 guardats en ordre creixent per les files (la primera fila té els valors del 1 al 4 i la última fila els valors del 17 al 20).
A partir d'aquest array, escriviu el codi per retornar altres arrays que continguin:
- La tercera fila de l'array
- Les dues últimes columnes de l'array
- El quadrat definit per la intersecció de les files 1 a 3 i les columnes 1 a 2 (extrems inclosos)
- El quadrat definit per la intersecció de les files 0, 2, 4 i les columnes 0, 2

In [31]:
a = np.array([np.arange(1,6), np.arange(6,11), np.arange(11, 16), np.arange(16,21)])
print(a)
print(a[2,:])
print(a[:,3:5])
print(a[:,-2:])
print(a[1:4, 1:3])
print(a[0:3:2, 0:3:2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[11 12 13 14 15]
[[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]]
[[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]]
[[ 7  8]
 [12 13]
 [17 18]]
[[ 1  3]
 [11 13]]


### **Arrays: Cerca**

Igual que a les llistes: operador `in` retorna `True` si un element està dins de l'array

In [32]:
import numpy as np
a = np.array([np.arange(0,10,2), np.arange(1,10,2), np.arange(10,20,2)])
print(a)

x = int(input())

if x in a:
	print(x, 'esta a l’array')
else:
	print(x, 'no esta a l’array')

[[ 0  2  4  6  8]
 [ 1  3  5  7  9]
 [10 12 14 16 18]]


 4


4 esta a l’array


**Exercici**: Modifiqueu el codi anterior per comprovar si el valor *x* està dins d'una determinada columna de l'array. L'índex de la columna també s'ha de llegir per teclat

In [33]:
import numpy as np
a = np.array([np.arange(0,10,2), np.arange(1,10,2), np.arange(10,20,2)])
print(a)

x = int(input())
col = int(input())

if x in a[:, col]:
	print(x, 'esta a l’array')
else:
	print(x, 'no esta a l’array')

[[ 0  2  4  6  8]
 [ 1  3  5  7  9]
 [10 12 14 16 18]]


 4
 0


4 no esta a l’array


### **Arrays: Recorregut**

In [ ]:
a = np.array([np.arange(0,10,2), np.arange(1,10,2), np.arange(10,20,2)])
for fila in a:
    print(fila)

#### **Recorregut per cada dimensió de l'array:**
- Similar a les llistes en arrays 1D

In [34]:
a = np.array(np.arange(0,10,2))
print(a)
for valor in a:
    print(valor)

[0 2 4 6 8]
0
2
4
6
8


- En arrays 2D, primer per files i després per columnes

In [35]:
a = np.array([np.arange(0,10,2), np.arange(1,10,2), np.arange(10,20,2)])
for fila in a:
    print(fila)

[0 2 4 6 8]
[1 3 5 7 9]
[10 12 14 16 18]


In [36]:
a = np.array([np.arange(0,10,2), np.arange(1,10,2), np.arange(10,20,2)])
for fila in a:
    for element in fila:
        print (element," ", end="")
    print ("\n")

0  2  4  6  8  

1  3  5  7  9  

10  12  14  16  18  



#### **Recorregut de tots els elements de l'array en un sol bucle:**
```python
a.flat
```
retorna un array 1D amb tots els elements de l'array recorreguts per files

In [37]:
a = np.array([np.arange(0,10,2), np.arange(1,10,2), np.arange(10,20,2)])
for x in a.flat:
    print(x)

0
2
4
6
8
1
3
5
7
9
10
12
14
16
18


#### **Recorregut recuperant valors i índexs de l'array**
```python
np.ndenumerate(a)
```
- Similar a `enumerate` per llistes
- `index` recorre l’índex com una tupla (fila, columna) de tots els elements de l’array
- `element` recorre tots els elements de l’array

In [38]:
a = np.array([np.arange(0,10,2), np.arange(1,10,2), np.arange(10,20,2)])
for index, element in np.ndenumerate(a):
    print (index, element)

(0, 0) 0
(0, 1) 2
(0, 2) 4
(0, 3) 6
(0, 4) 8
(1, 0) 1
(1, 1) 3
(1, 2) 5
(1, 3) 7
(1, 4) 9
(2, 0) 10
(2, 1) 12
(2, 2) 14
(2, 3) 16
(2, 4) 18


### **Arrays: afegir/eliminar elements**
- Es fa de forma similar a les llistes

#### **Afegir elements amb la funció `insert`**

- Retorna un array resultat d'afegir el valor o valors a les posicions indicades per l’índex.

```python
np.insert(array, index, valor)
```

In [40]:
a = np.arange(3)
print(a)
a = np.insert(a, 1, -1)
print(a)
a = np.insert(a, 2, [-2, -3])
print(a)

[0 1 2]
[ 0 -1  1  2]
[ 0 -1 -2 -3  1  2]


#### **Afegir elements amb la funció `append`**

- Retorna un array resultat d'afegir el valor o valors al final de l’array.

```python
np.append(array, valor)
```

In [39]:
a = np.arange(3)
print(a)
a = np.append(a, -3)
print(a)
a = np.append(a, [-1, -2])
print(a)

[0 1 2]
[ 0  1  2 -3]
[ 0  1  2 -3 -1 -2]


#### **Eliminar elements amb la funció `delete`**

- Elimina l’element de la posició indicada per l’índex.

```python
np.delete(array, index)
```

In [41]:
a = np.arange(3)
print(a)
a = np.delete(a, 0)
print(a)

[0 1 2]
[1 2]
