# **Arrays - Mòdul Numpy**

- Mòdul per treballar amb arrays (tipus `ndarray`)


In [2]:
import numpy as np

### **Operacions aritmètiques i de comparació**

- Les operacions matemàtiques complexes i costoses s’implementen en llenguatges compilats com C o Fortran. S’executen de forma molt eficient.
- Operen element per element de l’array
- Poden ser entre dos arrays o entre un array i un escalar
- Es poden encadenar operacions sobre matrius sempre que el resultat sigui també una matriu
- Podem fer servir qualsevol operació aritmètica o de comparació habitual

https://docs.scipy.org/doc/numpy/user/quickstart.html#basic-operations

In [3]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[0, 2, 4], [1, 3, 5]])
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[0 2 4]
 [1 3 5]]


In [4]:
print (a + b)

[[ 1  4  7]
 [ 5  8 11]]


In [5]:
print (a * b)

[[ 0  4 12]
 [ 4 15 30]]


In [6]:
print (a * 2)

[[ 2  4  6]
 [ 8 10 12]]


In [ ]:
print (((a + b)*2)-5)

In [7]:
print (a**2)

[[ 1  4  9]
 [16 25 36]]


In [8]:
print(a == b)

[[False  True False]
 [False False False]]


In [9]:
print (a < 3)

[[ True  True False]
 [False False False]]


In [10]:
print(a < b)

[[False False  True]
 [False False False]]


Fixem-nos que les operacions de comparació retornen un altre array. Si volem retornar un sol valor lògic hem d'utilitzar les funcions `all` i `any`
- `all`: retorna `True` si tots els elements de l'array són `True`
- `any`: retorna `True` si algun element de l'array és `True`

In [11]:
print(np.all(a == b))

False


In [12]:
print(np.any(a == b))

True


In [13]:
print(np.any(a < b))

True


In [14]:
print(np.all(a < 10))

True


### **Propietats i funcions sobre els arrays**

https://docs.scipy.org/doc/numpy/user/quickstart.html#functions-and-methods-overview
https://docs.scipy.org/doc/numpy/user/quickstart.html#universal-functions

#### **Recuperar dimensions i nº d'elements de l'array**

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
# Retorna dimensions de l’array
print (a.shape)
# Retorna nº elements de l’array
print (a.size)

#### **Operacions sobre tots els elements de l'array (suma, mínim, màxim, mitja, ...)**

In [15]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print (a.sum(), a.min(), a.max(), a.mean())

21 1 6 3.5


In [16]:
print(a)
# Suma recorrent la dimensió 0 (files): retorna la suma de cada columna
print (a.sum(0))
# Suma recorrent la dimensió 1 (columnes): retorna la suma de cada fila
print (a.sum(1))
# Podem fer el mateix per totes les funcions: max, min, mean, ...

[[1 2 3]
 [4 5 6]]
[5 7 9]
[ 6 15]


<img src="./imatges_notebook/image3.png" alt="image 3" width="100" height="100" > 

In [17]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print (np.sqrt(a))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [18]:
print (np.exp(a))

[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]


In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 2], [3, 4], [5, 6]])
print(a)
print(b)
# Multiplicació de matrius
print (np.dot(a,b))