# **Arrays - Mòdul Numpy**

- Mòdul per treballar amb arrays (tipus `ndarray`)


In [1]:
import numpy as np

### Variar la forma d'un array

#### Canvi de les dimensions de l'array

In [2]:
a = np.arange(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


**`reshape`**
- Reorganitza els elements de l’array a en un nou array amb les dimensions especificades
- Els elements de l’array a es posen per files al nou array seguint l’ordre original

In [3]:
b = a.reshape(3,4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [4]:
c = b.reshape(2, 2, 3)
print(c)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


**`flatten`**
- Posa tots els elements de l’array en un nou array 1D de forma seqüencial

In [5]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = a.flatten()
print(b)

[1 2 3 4 5 6]


### Còpies de Variables o referències

In [6]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = a

print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


Si ara modifiquem l'array b...

In [7]:
b[0] = 2

print(b)
print(a)

[[2 2 2]
 [4 5 6]]
[[2 2 2]
 [4 5 6]]


Veiem que no tenim dos objectes diferents sinó que tenim dues referències al mateix objecte: 
a i b fan referència al mateix array.

**`copy`**

- Fa una còpia de tota l’estructura de forma recursiva amb tots els seus components:

In [8]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.copy(a)
b[0]=2

print(b)
print(a)

[[2 2 2]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


### Indexació amb arrays booleans

https://docs.scipy.org/doc/numpy/user/quickstart.html#indexing-with-boolean-arrays

In [9]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a < 3) # Retorna un array de booleans indicant quins elements són més petits que 3

[[ True  True False]
 [False False False]]


- Podem utilitzar arrays de booleans per seleccionar elements de l’array que compleixen alguna condició

In [10]:
b = a < 3
print(a[b]) # Mostra els elements que són més petits que 3 (True a l'array de booleans b)

[1 2]


In [11]:
a[a<3] = 0 # Modifica només els elements de l'array a que compleixen la condició de ser més petits que 3
print(a)

[[0 0 3]
 [4 5 6]]


- Podem combinar arrays de booleans amb els operadors `+` (equivalent a l'operador lògic `or`) i `*` (equivalent a l'operador lògic `and`)

In [12]:
a = np.array([2, 0, 3, 4, 5, 6, 1, 0, 4, 0])
b = np.array([0, 2, 3, 2, 6, 7, 2, 0, 3, 5])
c = ((a != 0) * (b != 0))
print(a[c])
print(b[c])

[3 4 5 6 1 4]
[3 2 6 7 2 3]


In [13]:
c = ((a == 0) + (b == 0))
print(a[c])
print(b[c])

[2 0 0 0]
[0 2 0 5]


### Indexació amb arrays d'índexos

Podem utilitzar arrays d’índexos per seleccionar determinats elements de l’array. 
- El primer array correspon als índexos de les files i el segon als índexos de les columnes dels elements a seleccionar.
- L'array resultat tindrà la mateixa dimensió que els arrays d'índexos. 
- Cada element correspondrà al valor que hi ha a fila i columna de l'array original que defineixen els índexos. 

https://docs.scipy.org/doc/numpy/user/quickstart.html#indexing-with-arrays-of-indices

In [14]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
i_files = np.array([0, 1, 2])
i_columnes = np.array([0, 1, 2])
# En aquest cas seleccionem els elements de la diagonal de la matriu (0,0), (1,1) i (2, 2)
print (a[i_files, i_columnes])

[1 5 9]


In [16]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)
i_files = np.array([[0,0], [1,1], [2, 2]])
i_columnes = np.array([[1, 2], [0, 2], [0, 1]])
# En aquest cas seleccionem els elements de les posicions que no estan a la diagonal i els retornem com una matriu
print (a[i_files, i_columnes])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [4 6]
 [7 8]]
